# Generated by Django 6.0.3 on 2026-03-29 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_alter_task_owner_taskshare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskshare',
            name='category',
        ),
    ]
