# Generated by Django 6.0.3 on 2026-03-27 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('owner', 'name')},
        ),
    ]
